### ISSUE TITLE
Weird player model when holding efficiency checker tool in hand (multiplayer)

### ISSUE THREAD

**Issue by Joly0** [MarcioHuser/EfficiencyCheckerMod-SML3#1]
I am playing satisfactory multiplayer and added this mod yesterday (latest version for everything) and just found a very weird bug.

Its hard to discribe, so here are pictures

![image](https://user-images.githubusercontent.com/13993216/118693274-36e41380-b80b-11eb-881b-ceeb0f6affb9.png)
![image](https://user-images.githubusercontent.com/13993216/118693299-3b103100-b80b-11eb-9d7b-aee3ab89870d.png)

**Comment by Joly0** [comment]
![image](https://user-images.githubusercontent.com/13993216/118693684-980be700-b80b-11eb-85f8-19b7d56b92ee.png)
![image](https://user-images.githubusercontent.com/13993216/118693709-9e9a5e80-b80b-11eb-90a8-2c25110817f2.png)
![image](https://user-images.githubusercontent.com/13993216/118693750-a65a0300-b80b-11eb-882a-9596cd0e3a7c.png)
![image](https://user-images.githubusercontent.com/13993216/118693768-ab1eb700-b80b-11eb-82d8-3b5e8a1e0e98.png)

This only happens, when the checker tool is hold in hand

**Comment by MarcioHuser** [comment]
This is already known. Have no idea why or what causes that, since it uses the same model and specs from the regular Object Scanner 🤷‍♂️

**Comment by Joly0** [comment]
Hm, but ingame looks like the object scanner is a bit larger in hand, then the efficiency tool and the tools seems a bit off while holding it in the hand

**Comment by Joly0** [comment]
![image](https://user-images.githubusercontent.com/13993216/118715785-56d40100-b824-11eb-9492-b47fcacbfc78.png)
![image](https://user-images.githubusercontent.com/13993216/118715805-5d627880-b824-11eb-86f3-49528df05b6f.png)

Efficiency Tool first, object scanner second

**Comment by MarcioHuser** [comment]
No, that's due to differente FOV settings. You are not using the default 90 FOV. The equipent does not scale correctly with different FOV in use
