### ISSUE TITLE
Support for multi belt item export machines

### ISSUE THREAD

**Issue by snowboundmage2** [MarcioHuser/EfficiencyCheckerMod-SML3#10]
In the more milestones mod, and probably a number of other mods, some machines have multiple outputs, each belt in charge of a different output. Support for these machines is already partial, but it would if great if it were full.

Machine: Forester
Mod: More Milestones
![20220826183326_1](https://user-images.githubusercontent.com/85192202/186859905-45b00424-732e-42db-ba15-840aeb0f3362.jpg)
Icon/Item wrong, Injected Input is actually 30, required output is 180(vanilla constructor, vanilla leaves>biomass recipe)
![20220826183429_1](https://user-images.githubusercontent.com/85192202/186859921-135f3c77-79d1-471d-a685-d2ae39621136.jpg)
Icon/Item right, Injected Input is correct, required output is correct(vanilla constructor, vanilla wood>biomass recipe)
![20220826183430_1](https://user-images.githubusercontent.com/85192202/186859930-65f24b2e-0c00-4519-80bf-9d478d2cdd58.jpg)
Injected input is correct, Required output is incorrect(should be --, no connection), throughput is correct
![image](https://user-images.githubusercontent.com/85192202/186862580-118147d2-e56f-4bd3-9833-695d53547cc1.png)

**Comment by MarcioHuser** [comment]
It has been updated to take that into account

**Comment by snowboundmage2** [comment]
Very nice
