### ISSUE TITLE
Update to game broke hand tool

### ISSUE THREAD

**Issue by snowboundmage2** [MarcioHuser/EfficiencyCheckerMod-SML3#11]
EXP build 195135 hand tool works fine
EXP build 198647 hand tool broken

ECM v2.1.6
Updating to the latest EXP branch for the game(198647) has broken the hand tool. The device is invisible/not there in the players hand. Clicking on a belt with the invisi-tool doesn't make the device doesn't come back or anything. Hovering over anything interactable makes the interactable outline/hud element flicker until I aim away. Crafting a new one doesn't help. The ECM buildings seem unaffected so far.

**Comment by MarcioHuser** [comment]
I am aware, they must have changed the model for the Object Scanner in the code (I reuse that as it is in the game). I won't have many free time to be able to check it out anytime soon, though, but I will when I can

**Comment by MarcioHuser** [comment]
Fixed
