### ISSUE TITLE
Game crashing on load

### ISSUE THREAD

**Issue by Nikademus** [MarcioHuser/EfficiencyCheckerMod-SML3#12]
Haven't played since maybe mid-July, just fired up my old save.  It crashes everytime I load Efficiency Checker.  Using 2.1.6 on Experimental.  Disabling the mod allows the save to load.

Version: 199000, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Standalone, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000002

FactoryGame_FactoryGame_Win64_Shipping!AFGBuildable::GetActiveSkin_Native() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:639]
FactoryGame_FactoryGame_Win64_Shipping!UFGColoredInstanceMeshProxy::InstantiateInternal() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGColoredInstanceMeshProxy.cpp:117]
FactoryGame_Engine_Win64_Shipping!AActor::BeginPlay() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:3620]
FactoryGame_FactoryGame_Win64_Shipping!AFGBuildable::BeginPlay() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildable.cpp:203]
FactoryGame_EfficiencyCheckerMod_Win64_Shipping!AEfficiencyCheckerBuilding::BeginPlay() [E:\SFModding\SML3\Plugins\EfficiencyCheckerMod\Source\EfficiencyCheckerMod\Private\EfficiencyCheckerBuilding.cpp:60]
FactoryGame_Engine_Win64_Shipping!AActor::DispatchBeginPlay() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:3569]
FactoryGame_Engine_Win64_Shipping!AWorldSettings::NotifyBeginPlay() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\WorldSettings.cpp:247]
FactoryGame_FactoryGame_Win64_Shipping!AFGWorldSettings::NotifyBeginPlay() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGWorldSettings.cpp:437]
FactoryGame_Engine_Win64_Shipping!AGameMode::HandleMatchHasStarted() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\GameMode.cpp:239]
FactoryGame_Engine_Win64_Shipping!AGameMode::SetMatchState() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\GameMode.cpp:355]
FactoryGame_Engine_Win64_Shipping!UWorld::BeginPlay() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\World.cpp:4463]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:13263]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12465]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12663]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-220602145101-842\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-220602145101-842\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by MarcioHuser** [comment]
It has been fixed now
