### ISSUE TITLE
EfficiencyChecker show: error

### ISSUE THREAD

**Issue by AtrejaAlwinnen** [MarcioHuser/EfficiencyCheckerMod-SML3#13]
I use the spimple conveyor mod with no problems.
However, if the input from a conveyor belt exceeds 3300 units, the EfficiencyChecker only shows: error
Is there a possibility to change that?
![error](https://user-images.githubusercontent.com/72468128/190711378-25fb88e2-e092-4ec3-b5bc-31dff3201de5.jpg)

**Comment by MarcioHuser** [comment]
An error message is shown if the logic takes too long to complete or if there are too many mergers/splitters. It protects itself to prevent game to hang or crash

**Comment by AtrejaAlwinnen** [comment]
Ah okay. I didn't know that, I thought it had something to do with the maximum input of the conveyor belts. My building concept requires a lot of splinters and mergers. 
Maybee you can increase the limit a bit?
Or add an option to configure the limit in Option menu?
btw. Great mod without which I would be very reluctant to continue playing.. ;)

**Comment by MarcioHuser** [comment]
I can't, it is a game limit. If there are too many splittings/merging, all interconected, it can surpass the amount of recursion the game code allows, and if I go being it,it will crash the game. This limit cannot be circumvented.
But, if you have too long line of belts, you can increase the check timeout, by editing the file (Satisfactory folder)\FactoryGame\Configs\EfficiencyCheckerMod.cfg
![image](https://user-images.githubusercontent.com/68478105/190726006-8398d328-47c7-4060-b587-7462e4c5d77c.png)

**Comment by AtrejaAlwinnen** [comment]
Too bad. Unfortunately, increasing the timeout limit doesn't help, so it's probably due to the number of mergers (about 110). Then it just has to go like this, or I'll rebuild over a large area.. :) Thanks for the quick reply.
