### ISSUE TITLE
[Bug?] [2.0.9] Pipe efficiency checkers don't take valves into account

### ISSUE THREAD

**Issue by maskedmouse** [MarcioHuser/EfficiencyCheckerMod-SML3#2]
I've got a pipe network where I split off in branches. When placing an efficiency checker on the pipe it doesn't seem to take into account that there are valves put in front as the Injected input is 1500 m³/min.

Is this a bug or perhaps has this not been implemented yet?

**Comment by MarcioHuser** [comment]
I've noticed it before, haven't had time to have a look into it, yet. It just considers the valve as if it was any regular "inline pump":

- checker -> pump/valve -> only consider consumers at this point
- checker <- pump/valve <- only consider producers at this point

**Comment by MarcioHuser** [comment]
It has been fixed for a while, now
