### ISSUE TITLE
Any chance to make this work with Storage Teleporter?

### ISSUE THREAD

**Issue by StrikerTwo** [MarcioHuser/EfficiencyCheckerMod-SML3#21]
Would be cool if Efficiency Checker would work together with Storage Teleporter (https://ficsit.app/mod/StorageTeleporter).
As it is now it won't even calculate the demand of the machines that are supplied by a teleporter.

Thanks in advance, and thanks for pushing out a quick patch for update 8! Once you get used to EC you don't want to live without it ;)

**Comment by MarcioHuser** [comment]
It used to work fine with it. But it has been a long time since the last time I checked the compatibility for that mod. I may have a look into it next week

**Comment by MarcioHuser** [comment]
Compatibility restored
