### ISSUE TITLE
Still problems with recipes with more than one ingredient

### ISSUE THREAD

**Issue by StrikerTwo** [MarcioHuser/EfficiencyCheckerMod-SML3#23]
Hi,

I still have the problem (with 2.4.6) that belts running into e.g. an assembler show ALL the ingredients for the recipe, even if there is only one type of item injected into the belt.
I tried putting smart splitters in front of the efficiency checkers to filter the input, but then I get no item count at all on the display.

This is on a new game with no other storage-related mods active.

**Comment by StrikerTwo** [comment]
Okay, to clarify: 
I have a belt running from a steel beam factory to my central storage.
On the way there is a splitter from the belt to an assembler creating reinforced industrial beams from steel beams and concrete.

Further down the steel beam belt the efficiency checkers show both steel beams and concrete, even though there never is concrete on that belt.

**Comment by MarcioHuser** [comment]
It doesn't matter, it goes up and down throught the mergers/splitters and end up listing everytihng it "sees" in the way

**Comment by StrikerTwo** [comment]
Okay, but in this case the only place it can see the concrete is inside the assembler. There is no splitting or merging of the ingredients together along the way.

**Comment by StrikerTwo** [comment]
So I did some more testing and it looks like the problem only occurs if there is a smart splitter somewhere in the line.
(I put those on the outputs of my factories in order to sink all the overflow at the source.)

If I use the efficiency checker hand tool before the smart splitter, all is fine and it only shows one item, the output of the factory.
![Screenshot20231228-10405300000](https://github.com/MarcioHuser/EfficiencyCheckerMod-SML3/assets/6770084/483ab75a-2221-4f97-aa32-020981bc99cd)

If I use it on a belt on the "any" exit of the smart splitter (or a filtered output, does not matter), it shows me all the ingredients of the recipes of all the machines down the line.
![Screenshot20231228-10410200000](https://github.com/MarcioHuser/EfficiencyCheckerMod-SML3/assets/6770084/34ed1204-a806-4e82-b347-cd3ba9db6732)

**Comment by swaglogger** [comment]
> It doesn't matter, it goes up and down throught the mergers/splitters and end up listing everytihng it "sees" in the way

Still seeing this issue today. There is definitely an issue with the smart splitters. Regular splitters and mergers are fine but as soon as a smart splitter is on the line whether it's set to "Any" or "overflow" the numbers and item pics are off

**Comment by MarcioHuser** [comment]
It should be fixed, now
