### ISSUE TITLE
Efficiency Checker showing negative injected input & multiple items on single item belts

### ISSUE THREAD

**Issue by sbrocket** [MarcioHuser/EfficiencyCheckerMod-SML3#25]
Efficiency Checker seems to produce erroneous output after splitters in certain scenarios, showing both a negative value for injected input and multiple items for a belt that only ever contains one item and where the only possible connections to belts with other items are through production machines.

Created this recording to show the issue while hopefully capturing enough context so it's apparent this isn't a "user holding it wrong" issue, https://www.youtube.com/watch?v=IgVrP9QwM5o, but let me know if there's any other useful info I can provide. Oddly enough the values seem correct on the belts at the output of the Iron Rod constructors and at any point in between or directly after those output mergers, 90 input but 110 max output is accurate, but then the values make little sense after the 1st manifold splitter into the Screw Constructors, where that first splitter also splits part of the rods out for use in the Rotor Assemblers.

May be related to the Assemblers (producing Rotors using the default recipe) that the Iron Rods and Screws both flow into? Towards the end of the video I show it happening with Screws + Iron Plates as well, which are the ingredients to the 3rd Assembler shown which is using the default Reinforced Iron Plate recipe.

I haven't discerned the pattern in the negative injected input values though, no idea what's going on there.

**Comment by MarcioHuser** [comment]
that error is mapped and a fix is being worked on

**Comment by MarcioHuser** [comment]
It should be fixed, now
