### ISSUE TITLE
Please add documentation for how values behave across splitters and mergers

### ISSUE THREAD

**Issue by sbrocket** [MarcioHuser/EfficiencyCheckerMod-SML3#26]
It would be helpful to new and potential users if you could add some explanation to the mod description explaining how the values that the mod displays (Injected Input, Required Output) are expected to behave across splitters and mergers. Input across mergers and output across splitters is obvious, those are just sums, but the other pairings - the logic for how input is split downstream of a splitter and how required output is split upstream of a merger - are much less obvious. I've only been able to partially work it out through observation (and which is itself made harder due to issues like https://github.com/MarcioHuser/EfficiencyCheckerMod-SML3/issues/25).

Tangentially related: A screenshot or two in the description would be really useful too. I had no idea what exactly this displayed and how until I actually installed the mod, and I only did so without first knowing that because I've seen it mentioned so much elsewhere.

**Comment by MarcioHuser** [comment]
Values are not precise, there's a bug in the code that is not considering the correct values when measuring after a splitter

**Comment by MarcioHuser** [comment]
It should be fixed, now
