### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by mnsnownutt** [MarcioHuser/EfficiencyCheckerMod-SML3#27]
V2.5.1
Game crashes while loading with the following error message:

![error](https://github.com/user-attachments/assets/2bd903dd-e95e-4e1c-aca5-2d15f87160a1)

**Comment by MILLIUMMUSIC** [comment]
same on windows but working perfectly on mac through crossover.

**Comment by imibion** [comment]
Same error. Win10, steam version, upd 1.0.0.4, 
ModLoader v.3.8.0+483

**Comment by MarcioHuser** [comment]
Today's game patch broken this mod and Mass Upgrade. And maybe some others. I have to wait for the SML update to be able to deploy a fix
