### ISSUE TITLE
Can’t obtain the modules/buldings

### ISSUE THREAD

**Issue by SirGrady** [MarcioHuser/EfficiencyCheckerMod-SML3#28]
Hiya,

I was already Tier 8 when I installed this mod. Now, after selecting the corresponding milestone for this mod, I can’t add any resources to fulfill it. No dragging and no double clicking works.

Any solution ?

Greets,
Grady

**Comment by MarcioHuser** [comment]
None. I just set the cost for the milestone, it is up to the game to do the rest 🤷🏽‍♂️

**Comment by SirGrady** [comment]
I understand. But what can i do now that i am far beyond the milestones for this mod ?

I assume that I am not the only one, since mod support under 1.0 was only restored late and many are already further along in the milestones.

There should be an option or an switch or something like "if milestone > 6 give it for free"
Or even better: "append to current milestone/tier"

Grady

**Comment by MarcioHuser** [comment]
That's just simply a thing I am not able to do 🤷🏽‍♂️

**Comment by MarcioHuser** [comment]
I will close this case. I have received reports about that same issue at the Discord Server and the person solved it be reinstalling the mod
