### ISSUE TITLE
Game Crashes After Ficsmas Update

### ISSUE THREAD

**Issue by waldo808** [MarcioHuser/EfficiencyCheckerMod-SML3#3]
After updating to version v0.5.1.3 the game crashes if the mod is enabled. I have included the crash diagnostic info if that is helpful! This is when the only mod installed is Efficiency Checker.

I love the mod and appreciate all of the work you've put into it! Let me know if there is any other information that would be helpful!

[Crash_Diagnostics.txt](https://github.com/MarcioHuser/EfficiencyCheckerMod-SML3/files/7629955/Crash_Diagnostics.txt)
d.

**Comment by MarcioHuser** [comment]
I am already aware about that. It will be updated when I have time to have a look into that

**Comment by waldo808** [comment]
It is working after the fix, thank you!
