### ISSUE TITLE
Crashing after selecting any checker in build menu.

### ISSUE THREAD

**Issue by imibion** [MarcioHuser/EfficiencyCheckerMod-SML3#30]
Win10, steam version, upd 1.0.0.5,
ModLoader v.3.8.0+483
Crashing after selecting any EfChecker in build menu (or using MidMB to copy existing one)
:(

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000038
Crash log attached.
[2024-11-05_sf_crash_log.txt](https://github.com/user-attachments/files/17624306/2024-11-05_sf_crash_log.txt)

**Comment by MarcioHuser** [comment]
The game got patched today and many mods are crashing now. Have to wait

**Comment by imibion** [comment]
Fixed wth today update (v2.5.5), thank you.
