### ISSUE TITLE
[Feature Request] - Ignore Stand-By

### ISSUE THREAD

**Issue by TeamBaDBob** [MarcioHuser/EfficiencyCheckerMod-SML3#4]
Hey, your mod just helped me fix my factory, thanks :)

i like to build for the future and add machines set to stand-by. the effiecency checker is including these in the calculations.
Is it possible to ignore these machines?

Thanks
(hope its ok to post this here)

**Comment by MarcioHuser** [comment]
It is possible for quite some time. With the hand tool you cycle through with the right mouse button. And at the belt/pipe checkers, by interacting with it and choosing the desired options at the bottom of the window

![image](https://user-images.githubusercontent.com/68478105/147688879-0a8d7a7f-a00a-4a57-9eed-1b5bf6b1e9f7.png)

**Comment by TeamBaDBob** [comment]
Oh, that's awesome... I didn't see that in the documentation.  Thanks for the quick response,  happy new year... I'm off to check all my factories now :)On Dec. 29, 2021 11:38 a.m., MarcioHuser ***@***.***> wrote:
It is possible for quite some time. With the hand tool you cycle through with the right mouse button. And at the belt/pipe checkers, by interacting with it and choosing the desired options at the bottom of the window
