### ISSUE TITLE
Doesn't work well with the Modular Load Balancer mod.

### ISSUE THREAD

**Issue by TonyFlury** [MarcioHuser/EfficiencyCheckerMod-SML3#5]
I use the MLLB mod as a space saver. If you place an ECM reporter on the output of a connected group of MLB, the stats on the ECM reporter only seem to report on the the input of the first device that the output is connected to - in other words it ignores the total inputs into the MLB.

For example I had a group of 6 MLB devices aggrgate 6 Mk1 belts with inputs of 20 ignots per minute  each into one belt of 120 ignots per minute; the output MK2 belt of the MLB group was attached to one of the MLB devices. The ECM device correctly reported that the throughput limit was 120 per min (based on the belt size), but reported the injected throughput as only 20 (i.e the input into the modular device that the output is connected to.

I don't know if this a problem with how the MLB reports it's stats or whether the ECM mod needs work to handle the MLB modules.

**Comment by matthewgdv** [comment]
Seconded, compatibility with MLB would be a godsend!

**Comment by MarcioHuser** [comment]
I have looked into the mod and it does not expose the modular groups, I have no way of knowing which belongs to what
