### ISSUE TITLE
Game crashes in U6 experimental?

### ISSUE THREAD

**Issue by syska** [MarcioHuser/EfficiencyCheckerMod-SML3#7]
My game crashes when launching using U6 experimental ... not sure if it's supposed to work or not.

This is the first time I try to use this mod ... also new to the game, but I think my brain needs this :-) ... not doing so many calculation all the time to see if my factory is running efficient.

**Comment by MarcioHuser** [comment]
It still does not work with U6. I am waiting for the SML update do be able to recompile and publish it again
