### ISSUE TITLE
Does not work with Underground Belts

### ISSUE THREAD

**Issue by StrikerTwo** [MarcioHuser/EfficiencyCheckerMod-SML3#8]
I love this mod, thank you for your work.
Unfortunately it does not work with Underground Belts (https://ficsit.app/mod/UndergroundBelts). It does not recognize items that are injected or consumed if an underground belt is used along the way. This is of course expected, because it's not a vanilla transport.

Is there any way you two could get together and make it work?

**Comment by esvarc** [comment]
It would be nice to have it implemented. Second for this.

**Comment by MarcioHuser** [comment]
Works with the mod, now
